import pool from '../config/postgre.js';

import createUpdatedAtTrigger
from '../utils/dbTrigger.js';


const createPaymentAttemptsTable = async () => {
    try{

        await pool.query(`
            CREATE EXTENSION IF NOT EXISTS pgcrypto;
        `);

        await pool.query(`
            CREATE TABLE IF NOT EXISTS payment_attempts (
                id UUID PRIMARY KEY
                    DEFAULT gen_random_uuid(),

                payment_id UUID NOT NULL
                    REFERENCES payments(id)
                    ON DELETE CASCADE,

                provider_name VARCHAR(30)
                    NOT NULL
                    DEFAULT 'razorpay'
                    CHECK (
                        provider_name IN (
                            'razorpay',
                            'stripe'
                        )
                    ),

                status VARCHAR(30)
                    NOT NULL
                    DEFAULT 'pending'
                    CHECK (
                        status IN (
                            'pending',
                            'processing',
                            'success',
                            'failed',
                            'cancelled'
                        )
                    ),

                amount NUMERIC(12,2) NOT NULL
                    CHECK (amount >= 0),

                currency VARCHAR(3)
                    NOT NULL
                    DEFAULT 'INR'
                    CHECK (
                        currency = UPPER(currency)
                    ),

                -- ID generated by payment provider
                provider_order_id VARCHAR(255),

                -- ID generated after actual payment
                provider_payment_id VARCHAR(255),

                -- Provider-specific failure information
                failure_code VARCHAR(100),

                failure_message TEXT,

                created_at TIMESTAMPTZ
                    NOT NULL
                    DEFAULT CURRENT_TIMESTAMP,

                updated_at TIMESTAMPTZ
                    NOT NULL
                    DEFAULT CURRENT_TIMESTAMP
            );
        `);

        await pool.query(`
            CREATE INDEX IF NOT EXISTS
            idx_payment_attempts_payment_id
            ON payment_attempts(payment_id);

            CREATE INDEX IF NOT EXISTS
            idx_payment_attempts_status
            ON payment_attempts(status);

            CREATE UNIQUE INDEX IF NOT EXISTS
            idx_payment_attempts_provider_order
            ON payment_attempts(provider_name, provider_order_id)
            WHERE provider_order_id IS NOT NULL;

            CREATE UNIQUE INDEX IF NOT EXISTS
            idx_payment_attempts_provider_payment
            ON payment_attempts(provider_name, provider_payment_id)
            WHERE provider_payment_id IS NOT NULL;
        `);

        await createUpdatedAtTrigger("payment_attempts");

        console.log("✅ Payment Attempts table created successfully.");

    }catch(error){

        console.error(
            "❌ Payment Attempts table creation failed",
            error
        );

        throw error;
    }
};


export default createPaymentAttemptsTable;